// Enrollment actions
export const SET_ENROLLMENT = 'SET_ENROLLMENT';
export const ADD_ENROLLMENT = 'ADD_ENROLLMENT';
export const UPDATE_ENROLLMENT = 'UPDATE_ENROLLMENT';
export const FETCH_ENROLLMENTS = 'FETCH_ENROLLMENTS';
export const DELETE_ENROLLMENT = 'DELETE_ENROLLMENT';
export const SET_SELECTED_ENROLLMENT = 'SET_SELECTED_ENROLLMENT';